### PR TITLE
Circuit diagram, GPIO connections

### LINKED ISSUE #6: Create a schema for target device
**Goal of the task:**

A project schema for the target device, thanks to which every member of the team will know how to construct
the device having needed parts and documentation.

**What functionality will it affect?**

sensors-and-screen

**Scope of the task:**

Create a schema including:
- mainboard (assuming RPI 3B due to unavailability of RPi0W2 on the market)
- power source such as powerbank or any other external battery. The power will be connected to
  board using Micro-USB header.
- PM sensor [PMSA003-C](https://botland.com.pl/czujniki-czystosci-powietrza/19587-czujnik-pylu-czystosci-powietrza-pm10-pm25-pm10-5v-uart-plantower-pmsa003-c-5904422379452.html) with [adapter](https://botland.com.pl/czujniki-czystosci-powietrza/13746-adapter-idc-10pin-127mm-jst-125mm-zlacza-v2-dla-czujnika-pms7003-5904422372187.html). This adapter allows to attach sensor
RPI GND, RX, TX pins (6,8,10), but then debugging will be much more difficult because thanks to connecting RPI to PC using UART,
we don't have to attach a keyboard or monitor, and it is easy to copy logs. In exchange, we can use a UART to USB converter and attach
it to RPI using it.
- temperature and pressure sensors
- couple of tact switches
- screen (I own [this](https://botland.com.pl/raspberry-pi-pico-hat-klawiatury-i-wyswietlacze/19715-wyswietlacz-lcd-ips-2-320x240px-spi-65k-rgb-do-raspberry-pi-pico-waveshare-19888-5904422347215.html)

**Resources and tips:**

- sensor datasheet - https://botland.com.pl/index.php?controller=attachment&id_attachment=4564
- RPI 3B pinout - https://www.etechnophiles.com/raspberry-pi-3-gpio-pinout-pin-diagram-and-specs-in-detail-model-b/
- Datasheet for other sensors and screens.

Remember that power should be split to the breadord. Also, we're having soldering iron if needed.

**Definition of Done:**

- PR to docs repo with the schema of the device

### PR DESCRIPTION
**Pull request by iwanicki92**

### CODE REVIEW

**Comment by esesyn01** [comment]
@iwanicki92 @ola567 It looks very good, please create a Markdown document in which you will put this image and add a short description of each component here.

Besides, why you finally decided to not attach adapter's SET and RESET pins?

**Comment by iwanicki92** [comment]
Why are we speaking English?
> Besides, why you finally decided to not attach adapter's SET and RESET pins?

Because they are not needed according to datasheet(sensor has it's own pull up/down resistor)

**Comment by esesyn01** [comment]
@iwanicki92 Ok, so add a Markdown document with image and description of all components.

> Why are we speaking English?

It's our convention. Let's be universal and talk in English, it may be helpful for someone in future

**Comment by esesyn01** [comment]
@iwanicki92 @ola567 Are you sure you can attach UART to GPIO14 and 15?

**Comment by esesyn01** [comment]
@iwanicki92 @ola567 As I told earlier, pins 8,10 (GPIO14,15) must be free, so debugging and connecting through UART will be possible. In order to connect the PM sensor, you may use a [UART to USB adapter](https://botland.com.pl/konwertery-usb-uart-rs232-rs485/4501-konwerter-usb-uart-pl2303-wtyk-usb-waveshare-4037-5903351248792.html), or find a way to use another pins as RX and TX for the sensor.

**Review by esesyn01 — APPROVED** [review]
Looks good to me

**Pull request merged**
